[package]
name = "dcrdrs"
version = "0.1.0"
authors = ["michael <utimichael9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
criterion = "0.3"

[features]
default = ["rpcclient"]
rpcclient = ["tungstenite", "native-tls", "reqwest"]

[[bench]]
name = "benches"
harness = false
path = "benches/lib.rs"

[dependencies]
dirs = "3.0.1"
base64 = "0.12.3"
reqwest = {version = "^0.10.8", optional = true}
native-tls = {version = "^0.2.4", optional = true}
tungstenite = {version = "^0.11.1", optional = true}
url = "*"
httparse = "*"
futures = "*"
async-std = "1.6.3"