[package]
name = "dcrdrs"
version = "0.1.0"
authors = ["michael <utimichael9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false
path = "benches/lib.rs"

[dependencies]
reqwest = {version = "*", features = ["socks"]}
tokio-tungstenite = "0.11.0"
dirs = "3.0.1"
base64 = "0.12.3"
bitcoin = "*"
warp = "*"
tokio = "*"
native-tls = "*"
tungstenite = {version = "^0.11.1", features = ["tls"]}
http = "*"
httparse = "*"
socks = "*"
url = "*"